import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from utils.api_clients import get_orders

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
[data-testid="stAppViewContainer"] { background: linear-gradient(135deg, #0a0e1a 0%, #0d1117 100%); }
[data-testid="stSidebar"] { background: linear-gradient(180deg, #0d1117 0%, #161b22 100%); border-right: 1px solid #21262d; }
.page-title { font-size: 2rem; font-weight: 700; background: linear-gradient(135deg, #3fb950, #58a6ff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.kpi-card { background: linear-gradient(135deg, #161b22, #1c2128); border: 1px solid #30363d; border-radius: 14px; padding: 20px; text-align: center; }
.kpi-val { font-size: 2rem; font-weight: 700; color: #58a6ff; }
.kpi-lbl { font-size: 0.8rem; color: #8b949e; text-transform: uppercase; letter-spacing: 1px; }
.badge { display: inline-block; padding: 3px 12px; border-radius: 20px; font-size: 0.75rem; font-weight: 600; }
.badge-draft { background: rgba(88,166,255,0.15); color: #58a6ff; border: 1px solid #58a6ff; }
.badge-delivered { background: rgba(63,185,80,0.15); color: #3fb950; border: 1px solid #3fb950; }
.badge-transit { background: rgba(210,153,34,0.15); color: #d29922; border: 1px solid #d29922; }
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="page-title">📋 Purchase Orders</div>', unsafe_allow_html=True)
st.markdown('<div style="color:#8b949e;margin-bottom:20px">Auto-generated by AI Agent based on ROP/EOQ optimization</div>', unsafe_allow_html=True)

orders = get_orders()
if not isinstance(orders, list) or not orders:
    st.info("No purchase orders yet. Use the Agent Chat to generate POs.")
    st.stop()

df = pd.DataFrame(orders)

# KPIs
c1, c2, c3, c4 = st.columns(4)
with c1:
    st.markdown(f'<div class="kpi-card"><div class="kpi-lbl">Total POs</div><div class="kpi-val">{len(df)}</div></div>', unsafe_allow_html=True)
with c2:
    n = df[df["status"] == "Draft"].shape[0]
    st.markdown(f'<div class="kpi-card"><div class="kpi-lbl">Draft</div><div class="kpi-val" style="color:#58a6ff">{n}</div></div>', unsafe_allow_html=True)
with c3:
    n = df[df["status"] == "In Transit"].shape[0]
    st.markdown(f'<div class="kpi-card"><div class="kpi-lbl">In Transit</div><div class="kpi-val" style="color:#d29922">{n}</div></div>', unsafe_allow_html=True)
with c4:
    n = df[df["status"] == "Delivered"].shape[0]
    st.markdown(f'<div class="kpi-card"><div class="kpi-lbl">Delivered</div><div class="kpi-val" style="color:#3fb950">{n}</div></div>', unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

col1, col2 = st.columns(2)
with col1:
    fig = px.pie(df, names="status", title="PO Status Distribution",
                 color="status",
                 color_discrete_map={"Draft": "#58a6ff", "In Transit": "#d29922", "Delivered": "#3fb950"})
    fig.update_layout(template="plotly_dark", height=350,
                      paper_bgcolor="rgba(22,27,34,0.8)",
                      font=dict(family="Inter", color="#c9d1d9"))
    st.plotly_chart(fig, use_container_width=True)

with col2:
    top = df.groupby("product")["quantity"].sum().reset_index().sort_values("quantity", ascending=False).head(8)
    fig2 = px.bar(top, x="quantity", y="product", orientation="h",
                  title="Top Products by Order Volume",
                  color="quantity", color_continuous_scale=["#1f6feb", "#a371f7"])
    fig2.update_layout(template="plotly_dark", height=350,
                       paper_bgcolor="rgba(22,27,34,0.8)",
                       font=dict(family="Inter", color="#c9d1d9"),
                       yaxis=dict(gridcolor="#21262d"), xaxis=dict(gridcolor="#21262d"),
                       coloraxis_showscale=False)
    st.plotly_chart(fig2, use_container_width=True)

# Filter & Table
st.markdown('<div style="font-size:1.1rem;font-weight:600;color:#e6edf3;margin:16px 0 10px">📄 All Purchase Orders</div>', unsafe_allow_html=True)
status_filter = st.selectbox("Filter by Status", ["All", "Draft", "In Transit", "Delivered"])
view = df if status_filter == "All" else df[df["status"] == status_filter]

st.dataframe(
    view[["id", "product", "supplier", "quantity", "status", "created_at"]].rename(columns={
        "id": "PO #", "product": "Product", "supplier": "Supplier",
        "quantity": "Qty", "status": "Status", "created_at": "Created At"
    }),
    use_container_width=True, height=350,
)
